# Generated by Django 4.1.6 on 2023-04-11 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_uploadfile_user_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
